import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Flip, ToastContainer } from 'react-toastify';

import StoreProvider from '@/context/StoreProvider';
import AuthContext from '@/context/AuthContext';

import 'react-toastify/dist/ReactToastify.css';
import './globals.scss';
import { auth } from '@/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="fr">
      <body className={inter.className}>
        <AuthContext session={session}>
          <StoreProvider>{children}</StoreProvider>
        </AuthContext>

        <ToastContainer
          position="bottom-center"
          autoClose={5000}
          limit={5}
          hideProgressBar
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          transition={Flip}
        />
      </body>
    </html>
  );
}
